from __future__ import annotations

import argparse
import hashlib
import html
import json
import re
import sys
import time
import urllib.error
import urllib.request
from datetime import datetime, timezone
from html.parser import HTMLParser
from pathlib import Path
from typing import Any, Mapping
from urllib.parse import urlparse


ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from app.url_safety import is_non_public_host, open_public_http_request

DEFAULT_API_BASE_URL = "https://ai-search.haeorumgift.com"
DEFAULT_TRIGGER_TITLE = "AI\uac80\uc0c9"
PREVIEW_INSERTION_MARKER = "Haeorum AI Search preview insertion generated by widget_integration_probe.py"
DATA_AUTO_INIT_BLOCKING_RISKS = {
    "no_search_input_candidate",
    "ambiguous_recommended_selectors",
    "external_widget_src_blocked_or_risky",
    "api_connect_src_blocked_or_risky",
    "unsafe_api_base_url",
    "unsafe_widget_src",
    "unsafe_page_url",
}
FALLBACK_FLOATING_RESOLVABLE_RISKS = {
    "no_search_input_candidate",
    "ambiguous_recommended_selectors",
}
SITE_SOURCE_FIELDS = (
    "widget_probe_sources",
    "widget_probe_source",
    "html_sources",
    "html_source",
    "page_sources",
    "page_source",
    "url",
)
SOURCE_VALUE_KEYS = ("source", "path", "file", "url")
SOURCE_VARIANT_KEYS = ("variant", "viewport", "device", "form_factor", "page_variant", "name")
SEARCH_TERMS = (
    "search",
    "query",
    "keyword",
    "kwd",
    "sword",
    "goods_search",
    "\uac80\uc0c9",
    "\uc0c1\ud488",
    "\ud0a4\uc6cc\ub4dc",
)
BAD_INPUT_TYPES = {"hidden", "submit", "button", "checkbox", "radio", "file", "image", "password", "reset"}
VOID_TAGS = {
    "area",
    "base",
    "br",
    "col",
    "embed",
    "hr",
    "img",
    "input",
    "link",
    "meta",
    "param",
    "source",
    "track",
    "wbr",
}


class ProbeHtmlParser(HTMLParser):
    def __init__(self) -> None:
        super().__init__(convert_charrefs=True)
        self.elements: list[dict[str, Any]] = []
        self.stack: list[int] = []

    def handle_starttag(self, tag: str, attrs: list[tuple[str, str | None]]) -> None:
        normalized = tag.lower()
        parent = self.stack[-1] if self.stack else None
        element = {
            "index": len(self.elements),
            "tag": normalized,
            "attrs": {str(name).lower(): value or "" for name, value in attrs},
            "parent": parent,
            "children": [],
            "text": "",
        }
        self.elements.append(element)
        if parent is not None:
            self.elements[parent]["children"].append(element["index"])
        if normalized not in VOID_TAGS:
            self.stack.append(element["index"])

    def handle_startendtag(self, tag: str, attrs: list[tuple[str, str | None]]) -> None:
        self.handle_starttag(tag, attrs)
        if self.stack and self.elements[self.stack[-1]]["tag"] == tag.lower():
            self.stack.pop()

    def handle_endtag(self, tag: str) -> None:
        normalized = tag.lower()
        while self.stack:
            index = self.stack.pop()
            if self.elements[index]["tag"] == normalized:
                break

    def handle_data(self, data: str) -> None:
        if self.stack:
            self.elements[self.stack[-1]]["text"] += data


def parse_html(body: str) -> list[dict[str, Any]]:
    parser = ProbeHtmlParser()
    parser.feed(body or "")
    return parser.elements


def attr(element: dict[str, Any], name: str) -> str:
    return str(element.get("attrs", {}).get(name.lower()) or "").strip()


def has_attr(element: dict[str, Any], name: str) -> bool:
    return name.lower() in (element.get("attrs") or {})


def style_declares_hidden(style: str) -> bool:
    normalized = re.sub(r"\s+", "", str(style or "").lower())
    return "display:none" in normalized or "visibility:hidden" in normalized or "visibility:collapse" in normalized


def element_has_hidden_class(element: dict[str, Any]) -> bool:
    hidden_classes = {"hidden", "hide", "d-none", "display-none", "sr-only", "visually-hidden", "screen-reader-text"}
    classes = {value.strip().lower() for value in attr(element, "class").split() if value.strip()}
    return bool(classes & hidden_classes)


def element_is_hidden(elements: list[dict[str, Any]], element: dict[str, Any]) -> bool:
    current: dict[str, Any] | None = element
    while current is not None:
        if has_attr(current, "hidden") or attr(current, "aria-hidden").lower() == "true":
            return True
        if style_declares_hidden(attr(current, "style")):
            return True
        if element_has_hidden_class(current):
            return True
        parent = current.get("parent")
        current = elements[parent] if parent is not None else None
    return False


def element_is_disabled_or_readonly(elements: list[dict[str, Any]], element: dict[str, Any]) -> bool:
    if has_attr(element, "disabled") or has_attr(element, "readonly") or attr(element, "aria-disabled").lower() == "true":
        return True
    current: dict[str, Any] | None = element
    while current is not None:
        if current.get("tag") == "fieldset" and has_attr(current, "disabled"):
            return True
        parent = current.get("parent")
        current = elements[parent] if parent is not None else None
    return False


def element_text(elements: list[dict[str, Any]], index: int) -> str:
    element = elements[index]
    parts = [str(element.get("text") or "")]
    for child in element.get("children", []):
        parts.append(element_text(elements, child))
    return " ".join(part.strip() for part in parts if part.strip())


def ancestor(elements: list[dict[str, Any]], index: int, tag: str) -> dict[str, Any] | None:
    parent = elements[index].get("parent")
    while parent is not None:
        candidate = elements[parent]
        if candidate.get("tag") == tag:
            return candidate
        parent = candidate.get("parent")
    return None


def descendants(elements: list[dict[str, Any]], index: int) -> list[dict[str, Any]]:
    found: list[dict[str, Any]] = []
    for child in elements[index].get("children", []):
        found.append(elements[child])
        found.extend(descendants(elements, child))
    return found


def haystack(element: dict[str, Any], extra: str = "") -> str:
    attrs = element.get("attrs", {})
    values = [
        element.get("tag", ""),
        attrs.get("id", ""),
        attrs.get("name", ""),
        attrs.get("class", ""),
        attrs.get("placeholder", ""),
        attrs.get("title", ""),
        attrs.get("aria-label", ""),
        attrs.get("value", ""),
        extra,
    ]
    return " ".join(str(value or "").lower() for value in values)


def contains_search_term(value: str) -> bool:
    lowered = str(value or "").lower()
    return any(term in lowered for term in SEARCH_TERMS)


def input_score(elements: list[dict[str, Any]], element: dict[str, Any]) -> int:
    if element.get("tag") not in {"input", "textarea"}:
        return 0
    input_type = attr(element, "type").lower() or "text"
    if input_type in BAD_INPUT_TYPES:
        return 0
    if element_is_hidden(elements, element) or element_is_disabled_or_readonly(elements, element):
        return 0
    score = 1
    if input_type == "search":
        score += 4
    if attr(element, "name").lower() in {"q", "query", "keyword", "sword", "search"}:
        score += 4
    for field in ("id", "name", "class", "placeholder", "title", "aria-label"):
        if contains_search_term(attr(element, field)):
            score += 2
    form = ancestor(elements, int(element["index"]), "form")
    if form and contains_search_term(haystack(form, attr(form, "action"))):
        score += 2
    return score


def button_score(elements: list[dict[str, Any]], element: dict[str, Any]) -> int:
    tag = element.get("tag")
    input_type = attr(element, "type").lower()
    if element_is_hidden(elements, element) or element_is_disabled_or_readonly(elements, element):
        return 0
    if tag == "button":
        if input_type and input_type not in {"submit", "button"}:
            return 0
        score = 2 if input_type in {"", "submit"} else 1
    elif tag == "input" and input_type in {"submit", "image", "button"}:
        score = 2
    else:
        return 0
    text = element_text(elements, int(element["index"]))
    for field in ("id", "name", "class", "title", "aria-label", "value"):
        if contains_search_term(attr(element, field)):
            score += 2
    if contains_search_term(text):
        score += 3
    return score


def css_quote(value: str) -> str:
    return '"' + str(value).replace("\\", "\\\\").replace('"', '\\"') + '"'


def selector_for(elements: list[dict[str, Any]], element: dict[str, Any], qualify_form: bool = True) -> str:
    tag = str(element.get("tag") or "")
    form = ancestor(elements, int(element["index"]), "form")
    element_id = attr(element, "id")
    if element_id:
        selector = f"#{element_id}"
    elif attr(element, "name"):
        selector = f"{tag}[name={css_quote(attr(element, 'name'))}]"
    elif attr(element, "class"):
        first_class = attr(element, "class").split()[0]
        selector = f"{tag}.{first_class}"
    elif form and attr(form, "id") and tag == "button" and (attr(element, "type").lower() in {"", "submit"}):
        selector = 'button[type="submit"]'
    elif form and attr(form, "id") and tag == "input" and attr(element, "type").lower() in {"submit", "image", "button"}:
        selector = f'input[type="{attr(element, "type").lower()}"]'
    else:
        selector = tag
    if qualify_form and form and attr(form, "id") and (element_id or selector.startswith(("button[", "input["))):
        return f"#{attr(form, 'id')} {selector}"
    return selector


def find_search_candidates(elements: list[dict[str, Any]]) -> list[dict[str, Any]]:
    candidates = []
    for element in elements:
        score = input_score(elements, element)
        if score < 3:
            continue
        form = ancestor(elements, int(element["index"]), "form")
        button_pool = descendants(elements, int(form["index"])) if form else elements[int(element["index"]) + 1 : int(element["index"]) + 12]
        buttons = [
            {"element": button, "score": button_score(elements, button)}
            for button in button_pool
            if button_score(elements, button) > 0
        ]
        buttons.sort(key=lambda item: (-item["score"], int(item["element"]["index"])))
        best_button = buttons[0]["element"] if buttons else None
        candidates.append(
            {
                "score": score,
                "input": {
                    "tag": element["tag"],
                    "id": attr(element, "id"),
                    "name": attr(element, "name"),
                    "type": attr(element, "type") or "text",
                    "placeholder": attr(element, "placeholder"),
                    "selector": selector_for(elements, element),
                },
                "submit": {
                    "tag": best_button["tag"],
                    "id": attr(best_button, "id"),
                    "type": attr(best_button, "type") or "submit",
                    "text": element_text(elements, int(best_button["index"])),
                    "selector": selector_for(elements, best_button),
                }
                if best_button
                else None,
                "form": {
                    "id": attr(form, "id"),
                    "name": attr(form, "name"),
                    "action": attr(form, "action"),
                    "selector": selector_for(elements, form, qualify_form=False),
                }
                if form
                else None,
            }
        )
    candidates.sort(key=lambda item: (-int(item["score"]), item["input"]["selector"]))
    return candidates


def duplicate_id_counts(elements: list[dict[str, Any]]) -> dict[str, int]:
    counts: dict[str, int] = {}
    for element in elements:
        element_id = attr(element, "id")
        if not element_id:
            continue
        counts[element_id] = counts.get(element_id, 0) + 1
    return {element_id: count for element_id, count in sorted(counts.items()) if count > 1}


def selector_id_references(selector: str) -> list[str]:
    text = str(selector or "")
    ids = re.findall(r"#([^\s>+~,\[.#]+)", text)
    return sorted(set(ids))


def selector_duplicate_id_refs(selector: str, duplicate_ids: dict[str, int]) -> dict[str, int]:
    return {
        element_id: duplicate_ids[element_id]
        for element_id in selector_id_references(selector)
        if element_id in duplicate_ids
    }


def selector_parts(selector: str) -> list[str]:
    text = str(selector or "").strip()
    if not text or any(token in text for token in [">", "+", "~", ","]):
        return []
    return [part for part in text.split() if part]


def selector_match_count(elements: list[dict[str, Any]], selector: str) -> int:
    parts = selector_parts(selector)
    if not parts:
        return 0
    return sum(1 for element in elements if element_matches_selector_chain(elements, int(element["index"]), parts))


def element_matches_selector_chain(elements: list[dict[str, Any]], index: int, parts: list[str]) -> bool:
    if not simple_selector_matches(elements[index], parts[-1]):
        return False
    parent = elements[index].get("parent")
    for part in reversed(parts[:-1]):
        while parent is not None and not simple_selector_matches(elements[parent], part):
            parent = elements[parent].get("parent")
        if parent is None:
            return False
        parent = elements[parent].get("parent")
    return True


def simple_selector_matches(element: dict[str, Any], selector: str) -> bool:
    text = str(selector or "").strip()
    if not text:
        return False
    attrs = element.get("attrs", {})
    selector_without_attrs = re.sub(r"\[[^\]]+\]", "", text)
    id_match = re.search(r"#([^\s>+~,\[.#]+)", selector_without_attrs)
    class_matches = re.findall(r"\.([^\s>+~,\[.#]+)", selector_without_attrs)
    tag = re.split(r"[#.]", selector_without_attrs, maxsplit=1)[0].strip().lower()
    if tag and element.get("tag") != tag:
        return False
    if id_match and attrs.get("id") != id_match.group(1):
        return False
    classes = set(str(attrs.get("class") or "").split())
    if any(class_name not in classes for class_name in class_matches):
        return False
    for attr_name, raw_value in re.findall(r"\[([^\]=\s]+)=((?:\"[^\"]*\")|(?:'[^']*')|[^\]]+)\]", text):
        expected = raw_value.strip().strip("\"'")
        if str(attrs.get(attr_name.lower()) or "") != expected:
            return False
    return True


def add_candidate_selector_evidence(
    candidates: list[dict[str, Any]],
    elements: list[dict[str, Any]],
    duplicate_ids: dict[str, int],
) -> list[dict[str, Any]]:
    for candidate in candidates:
        duplicate_refs = {}
        selector_match_counts = {}
        selector_multiple_matches = {}
        for key in ("input", "submit", "form"):
            selector = str((candidate.get(key) or {}).get("selector") or "")
            refs = selector_duplicate_id_refs(selector, duplicate_ids)
            if refs:
                duplicate_refs[key] = refs
            if selector:
                match_count = selector_match_count(elements, selector)
                selector_match_counts[key] = match_count
                if key in {"input", "submit"} and match_count > 1:
                    selector_multiple_matches[key] = match_count
        candidate["selector_duplicate_ids"] = duplicate_refs
        candidate["selector_match_counts"] = selector_match_counts
        candidate["selector_multiple_matches"] = selector_multiple_matches
        blocking_duplicate_refs = {
            key: value for key, value in duplicate_refs.items() if key in {"input", "submit"}
        }
        candidate["selector_blocking_duplicate_ids"] = blocking_duplicate_refs
        candidate["selectors_unique"] = not bool(blocking_duplicate_refs or selector_multiple_matches)
    return candidates


def url_origin(value: str) -> str:
    parsed = urlparse(str(value or "").strip())
    if not parsed.scheme or not parsed.hostname:
        return ""
    try:
        port = parsed.port
    except ValueError:
        return ""
    default_port = (parsed.scheme == "https" and port == 443) or (parsed.scheme == "http" and port == 80)
    port_text = "" if port is None or default_port else f":{port}"
    return f"{parsed.scheme}://{parsed.hostname}{port_text}"


def is_local_or_link_host(hostname: str | None) -> bool:
    return is_non_public_host(hostname)


def https_url_problem(value: str, *, field_name: str, allow_query: bool = False) -> str:
    text = str(value or "").strip()
    if not text:
        return f"{field_name} is required"
    if any(char.isspace() or ord(char) < 32 or ord(char) == 127 or char == "\\" for char in text):
        return f"{field_name} must not contain whitespace, control characters, or backslashes"
    parsed = urlparse(text)
    try:
        parsed.port
    except ValueError:
        return f"{field_name} must include a valid port"
    if parsed.scheme.lower() != "https" or not parsed.netloc or not parsed.hostname:
        return f"{field_name} must be an absolute HTTPS URL"
    if parsed.username is not None or parsed.password is not None:
        return f"{field_name} must not include credentials"
    if parsed.params or parsed.fragment or (parsed.query and not allow_query):
        return f"{field_name} must not include params, query, or fragment"
    if is_local_or_link_host(parsed.hostname):
        return f"{field_name} must not use non-public hosts"
    return ""


def parse_csp_directives(policy: str) -> dict[str, list[str]]:
    directives: dict[str, list[str]] = {}
    for raw_directive in str(policy or "").split(";"):
        parts = [part for part in raw_directive.strip().split() if part]
        if not parts:
            continue
        directives[parts[0].lower()] = parts[1:]
    return directives


def csp_script_sources(policy: str) -> list[str]:
    directives = parse_csp_directives(policy)
    return directives.get("script-src") or directives.get("default-src") or []


def csp_script_element_sources(policy: str) -> tuple[str, list[str]]:
    directives = parse_csp_directives(policy)
    for name in ("script-src-elem", "script-src", "default-src"):
        if name in directives:
            return name, directives[name]
    return "", []


def csp_inline_script_risky(sources: list[str]) -> bool:
    if not sources:
        return False
    return not any(
        token == "'unsafe-inline'" or token.startswith("'nonce-") or token.startswith("'sha")
        for token in sources
    )


def csp_host_matches(source_host: str, target_host: str) -> bool:
    source = source_host.strip().lower()
    target = target_host.strip().lower()
    if not source or not target:
        return False
    if source == target:
        return True
    if source.startswith("*."):
        suffix = source[1:]
        return target.endswith(suffix) and target != source[2:]
    return False


def csp_source_allows_widget_src(source: str, widget_src: str, page_url: str = "") -> bool:
    return csp_source_allows_target_url(source, widget_src, page_url)


def csp_source_allows_target_url(source: str, target_url: str, page_url: str = "") -> bool:
    token = str(source or "").strip()
    if not token or token in {"'none'", "'unsafe-inline'", "'unsafe-eval'", "'strict-dynamic'"}:
        return False
    if token.startswith("'nonce-") or token.startswith("'sha"):
        return False
    target = urlparse(target_url)
    if not target.scheme or not target.hostname:
        return False
    try:
        target_port = target.port
    except ValueError:
        return False
    if token == "*":
        return True
    if token == "https:":
        return target.scheme == "https"
    if token == "http:":
        return target.scheme == "http"
    if token == "'self'":
        return bool(page_url) and url_origin(page_url) == url_origin(target_url)
    if token.startswith("//"):
        token = f"{target.scheme}:{token}"
    if re.match(r"^https?://", token, re.IGNORECASE):
        parsed = urlparse(token)
        try:
            parsed_port = parsed.port
        except ValueError:
            return False
        if parsed.scheme and parsed.scheme != target.scheme:
            return False
        if not csp_host_matches(parsed.hostname or "", target.hostname or ""):
            return False
        if parsed_port is not None and parsed_port != target_port:
            return False
        source_path = parsed.path.rstrip("/")
        if source_path and source_path != "*":
            target_path = target.path.rstrip("/")
            return target_path == source_path or target_path.startswith(source_path + "/")
        return True
    if token.startswith("*.") or re.match(r"^[\w.-]+(?::\d+)?$", token):
        host_part, _, port_part = token.partition(":")
        expected_port = target_port or (443 if target.scheme == "https" else 80)
        if port_part and str(expected_port) != port_part:
            return False
        return csp_host_matches(host_part, target.hostname or "")
    return False


def csp_widget_src_allowed(policies: list[str], widget_src: str, page_url: str = "") -> bool:
    return not csp_widget_src_blocking_directives(policies, widget_src, page_url)


def csp_widget_src_blocking_directives(policies: list[str], widget_src: str, page_url: str = "") -> list[str]:
    blocking = []
    for policy in policies:
        directive_name, sources = csp_script_element_sources(policy)
        if sources and not any(csp_source_allows_widget_src(source, widget_src, page_url) for source in sources):
            blocking.append(directive_name or "script-src")
    return blocking


def csp_connect_sources(policy: str) -> tuple[str, list[str]]:
    directives = parse_csp_directives(policy)
    for name in ("connect-src", "default-src"):
        if name in directives:
            return name, directives[name]
    return "", []


def csp_api_connect_blocking_directives(policies: list[str], api_base_url: str, page_url: str = "") -> list[str]:
    blocking = []
    target = str(api_base_url or "").rstrip("/")
    if not target:
        return blocking
    for policy in policies:
        directive_name, sources = csp_connect_sources(policy)
        if sources and not any(csp_source_allows_target_url(source, target, page_url) for source in sources):
            blocking.append(directive_name or "connect-src")
    return blocking


def csp_reports_inline_script_risk(
    elements: list[dict[str, Any]],
    *,
    response_policies: list[str] | None = None,
    widget_src: str = "",
    api_base_url: str = "",
    page_url: str = "",
) -> dict[str, Any]:
    policies = []
    for element in elements:
        if element.get("tag") != "meta":
            continue
        if attr(element, "http-equiv").lower() != "content-security-policy":
            continue
        content = attr(element, "content")
        if content:
            policies.append(content)
    policies.extend(str(policy) for policy in (response_policies or []) if str(policy).strip())
    risky = False
    inline_blocking_directives = []
    for policy in policies:
        directive_name, sources = csp_script_element_sources(policy)
        if csp_inline_script_risky(sources):
            risky = True
            inline_blocking_directives.append(directive_name or "script-src")
    widget_src_text = str(widget_src or "").strip()
    widget_blocking_directives = (
        csp_widget_src_blocking_directives(policies, widget_src_text, page_url) if widget_src_text else []
    )
    widget_allowed = not widget_blocking_directives
    api_base_url_text = str(api_base_url or "").rstrip("/")
    api_connect_blocking_directives = (
        csp_api_connect_blocking_directives(policies, api_base_url_text, page_url) if api_base_url_text else []
    )
    api_connect_allowed = not api_connect_blocking_directives
    return {
        "inline_init_risky": risky,
        "inline_init_blocking_directives": sorted(set(inline_blocking_directives)),
        "external_widget_src_risky": bool(widget_src_text and not widget_allowed),
        "widget_src_blocking_directives": sorted(set(widget_blocking_directives)),
        "widget_src_allowed": widget_allowed,
        "widget_src": widget_src_text,
        "widget_src_origin": url_origin(widget_src_text),
        "api_connect_risky": bool(api_base_url_text and not api_connect_allowed),
        "api_connect_blocking_directives": sorted(set(api_connect_blocking_directives)),
        "api_connect_allowed": api_connect_allowed,
        "api_base_url": api_base_url_text,
        "api_base_url_origin": url_origin(api_base_url_text),
        "page_origin": url_origin(page_url),
        "policies": policies,
    }


def existing_widget_report(elements: list[dict[str, Any]], api_base_url: str) -> dict[str, Any]:
    scripts = []
    for element in elements:
        if element.get("tag") != "script":
            continue
        source = attr(element, "src")
        text = str(element.get("text") or "")
        data_auto_init = element.get("attrs", {}).get("data-hai-auto-init")
        if "widget.js" in source or "HaeorumAISearch" in text or data_auto_init is not None:
            scripts.append(
                {
                    "src": source,
                    "relative_src": bool(source and not re.match(r"^https?://", source, re.IGNORECASE)),
                    "data_auto_init": html_truthy_attr(data_auto_init),
                    "manual_init": "HaeorumAISearch" in text and ".init" in text,
                    "api_base_url_marker": bool(api_base_url and api_base_url.rstrip("/") in (source + text)),
                }
            )
    return {
        "found": bool(scripts),
        "scripts": scripts,
        "relative_widget_script": any(item["relative_src"] for item in scripts if "widget.js" in item["src"]),
    }


def html_truthy_attr(value: str) -> bool:
    text = str(value or "").strip().lower()
    return bool(value is not None and (text == "" or text in {"1", "true", "yes", "y", "on"}))


def build_data_auto_init_snippet(
    *,
    widget_src: str,
    mall_id: str,
    api_key: str,
    attach_to_search_input: str,
    attach_after_selector: str,
    trigger_title: str,
    fallback_floating: bool = False,
) -> str:
    attrs = [
        ("src", widget_src),
        ("data-hai-auto-init", "true"),
        ("data-mall-id", mall_id),
        ("data-api-key", api_key),
        ("data-attach-to-search-input", attach_to_search_input),
        ("data-attach-after-selector", attach_after_selector),
        ("data-fallback-floating", "true" if fallback_floating else ""),
        ("data-trigger-title", trigger_title),
    ]
    lines = ["<script"]
    for name, value in attrs:
        if value:
            lines.append(f"  {name}=\"{html.escape(str(value), quote=True)}\"")
    lines[-1] = lines[-1] + "></script>"
    return "\n".join(lines)


def build_fallback_floating_recommendation(
    *,
    widget_src: str,
    mall_id: str,
    api_key: str,
    trigger_title: str,
    blocking_risks: list[str],
    review_risks: list[str],
    url_validation_ok: bool,
    csp: dict[str, Any],
) -> dict[str, Any]:
    fallback_ready = url_validation_ok and not blocking_risks
    return {
        "mode": "fallback_floating",
        "ready": fallback_ready,
        "blocking_risks": sorted(blocking_risks),
        "review_risks": sorted(review_risks),
        "inline_init_avoided": True,
        "url_validation_ok": url_validation_ok,
        "attachToSearchInput": "",
        "attachAfterSelector": "",
        "fallbackFloating": True,
        "csp_widget_src_allowed": csp["widget_src_allowed"],
        "csp_api_connect_allowed": csp["api_connect_allowed"],
        "selectors_unique": True,
        "selector_match_counts": {},
        "selector_multiple_matches": {},
        "selector_duplicate_ids": {},
        "selector_blocking_duplicate_ids": {},
        "csp_allowlist_hint": (
            f"Allow {csp['widget_src_origin']} in "
            f"{(csp.get('widget_src_blocking_directives') or ['script-src'])[0]}"
            if csp["external_widget_src_risky"]
            else ""
        ),
        "csp_api_allowlist_hint": (
            f"Allow {csp['api_base_url_origin']} in "
            f"{(csp.get('api_connect_blocking_directives') or ['connect-src'])[0]}"
            if csp["api_connect_risky"]
            else ""
        ),
        "snippet": build_data_auto_init_snippet(
            widget_src=widget_src,
            mall_id=mall_id,
            api_key=api_key,
            attach_to_search_input="",
            attach_after_selector="",
            trigger_title=trigger_title,
            fallback_floating=True,
        ),
    }


def load_probe_site_configs(path: Path) -> list[dict[str, Any]]:
    raw = json.loads(path.read_text(encoding="utf-8"))
    sites = raw.get("sites", raw) if isinstance(raw, dict) else raw
    if not isinstance(sites, list):
        raise ValueError("representative site config must be a list or an object with a sites list")
    normalized = []
    for index, site in enumerate(sites, start=1):
        if not isinstance(site, dict):
            raise ValueError("representative site entries must be objects")
        mall_id = str(site.get("mall_id") or site.get("site_id") or "").strip()
        if not mall_id:
            raise ValueError(f"site #{index} requires mall_id or site_id")
        normalized.append({**site, "mall_id": mall_id})
    return normalized


def string_list(value: Any) -> list[str]:
    if value is None:
        return []
    if isinstance(value, list):
        return [str(item).strip() for item in value if str(item).strip()]
    text = str(value).strip()
    return [text] if text else []


def resolve_probe_source(source: str, base_dir: Path | None = None) -> str:
    text = str(source or "").strip()
    if not text or re.match(r"^https?://", text, re.IGNORECASE):
        return text
    path = Path(text)
    if path.is_absolute() or base_dir is None:
        return text
    return str(base_dir / path)


def probe_source_items(value: Any) -> list[Any]:
    if value is None:
        return []
    if isinstance(value, list):
        return value
    return [value]


def probe_source_value(item: Any) -> str:
    if isinstance(item, dict):
        for key in SOURCE_VALUE_KEYS:
            value = str(item.get(key) or "").strip()
            if value:
                return value
        return ""
    return str(item or "").strip()


def normalize_probe_variant(value: Any) -> str:
    text = str(value or "").strip().lower().replace("_", "-")
    if text in {"pc", "desktop", "desktop-page", "desktop-web", "web", "wide"}:
        return "desktop"
    if text in {"m", "mo", "mobile", "mobile-page", "phone", "smartphone"}:
        return "mobile"
    return ""


def infer_probe_variant(source: str) -> str:
    text = str(source or "").strip().lower()
    parsed_path = urlparse(text).path if re.match(r"^https?://", text, re.IGNORECASE) else text
    tokens = {token for token in re.split(r"[^a-z0-9]+", parsed_path) if token}
    if tokens & {"pc", "desktop", "web", "wide"}:
        return "desktop"
    if tokens & {"m", "mo", "mobile", "phone", "smartphone"} or "/_mobile/" in parsed_path.replace("\\", "/"):
        return "mobile"
    return ""


def probe_source_variant(item: Any, source: str) -> str:
    if isinstance(item, dict):
        for key in SOURCE_VARIANT_KEYS:
            variant = normalize_probe_variant(item.get(key))
            if variant:
                return variant
    return infer_probe_variant(source)


def probe_source_entries(site: dict[str, Any], base_dir: Path | None = None) -> list[dict[str, Any]]:
    for field_name in SITE_SOURCE_FIELDS:
        entries = []
        for source_index, item in enumerate(probe_source_items(site.get(field_name)), start=1):
            source = probe_source_value(item)
            if not source:
                continue
            entries.append(
                {
                    "source": resolve_probe_source(source, base_dir),
                    "raw_source": source,
                    "field": field_name,
                    "source_index": source_index,
                    "variant": probe_source_variant(item, source),
                }
            )
        if entries:
            return entries
    return []


def site_probe_sources(site: dict[str, Any], base_dir: Path | None = None) -> list[str]:
    return [entry["source"] for entry in probe_source_entries(site, base_dir=base_dir)]


def has_explicit_probe_source(entry: Mapping[str, Any]) -> bool:
    return str(entry.get("field") or "") != "url"


def is_remote_probe_source(source: str) -> bool:
    return bool(re.match(r"^https?://", str(source or ""), re.IGNORECASE))


def local_explicit_probe_source_variants(entries: list[dict[str, Any]]) -> set[str]:
    return {
        str(entry.get("variant") or "")
        for entry in entries
        if has_explicit_probe_source(entry) and not is_remote_probe_source(str(entry.get("source") or ""))
    }


def missing_pc_mobile_variants(entries: list[dict[str, Any]]) -> list[str]:
    variants = local_explicit_probe_source_variants(entries)
    if not variants:
        return []
    missing = []
    if "desktop" not in variants:
        missing.append("desktop")
    if "mobile" not in variants:
        missing.append("mobile")
    return missing


def has_local_explicit_probe_sources(entries: list[dict[str, Any]]) -> bool:
    return any(
        has_explicit_probe_source(entry) and not is_remote_probe_source(str(entry.get("source") or ""))
        for entry in entries
    )


def site_widget_src(site: dict[str, Any], api_base_url: str, explicit_widget_src: str) -> str:
    configured = str(site.get("widget_src") or site.get("widget_script_src") or explicit_widget_src or "").strip()
    if configured:
        return configured
    widget_script = str(site.get("widget_script") or "").strip()
    if not widget_script:
        return ""
    if re.match(r"^https?://", widget_script, re.IGNORECASE):
        return widget_script
    return f"{api_base_url.rstrip('/')}/{widget_script.lstrip('/')}"


def analyze_html_source(
    name: str,
    body: str,
    *,
    api_base_url: str = DEFAULT_API_BASE_URL,
    widget_src: str = "",
    mall_id: str = "replace-with-mall-id",
    api_key: str = "replace-with-public-api-key",
    trigger_title: str = DEFAULT_TRIGGER_TITLE,
    response_csp_policies: list[str] | None = None,
    page_url: str = "",
    allow_fallback_floating: bool = False,
) -> dict[str, Any]:
    normalized_api_base_url = str(api_base_url or DEFAULT_API_BASE_URL).rstrip("/")
    normalized_widget_src = str(widget_src or f"{normalized_api_base_url}/widget.js").strip()
    effective_page_url = str(page_url or "").strip()
    if not effective_page_url and re.match(r"^https?://", name, re.IGNORECASE):
        effective_page_url = name
    api_base_url_problem = https_url_problem(normalized_api_base_url, field_name="api_base_url")
    widget_src_problem = https_url_problem(normalized_widget_src, field_name="widget_src")
    page_url_problem = https_url_problem(effective_page_url, field_name="page_url", allow_query=True) if effective_page_url else ""
    elements = parse_html(body)
    duplicate_ids = duplicate_id_counts(elements)
    candidates = add_candidate_selector_evidence(find_search_candidates(elements), elements, duplicate_ids)
    csp = csp_reports_inline_script_risk(
        elements,
        response_policies=response_csp_policies,
        widget_src=normalized_widget_src,
        api_base_url=normalized_api_base_url,
        page_url=effective_page_url,
    )
    existing_widget = existing_widget_report(elements, normalized_api_base_url)
    risks = []
    if not candidates:
        risks.append("no_search_input_candidate")
    if candidates and not candidates[0].get("submit"):
        risks.append("no_submit_anchor_candidate")
    if csp["inline_init_risky"]:
        risks.append("inline_init_blocked_or_risky")
    if csp["external_widget_src_risky"]:
        risks.append("external_widget_src_blocked_or_risky")
    if csp["api_connect_risky"]:
        risks.append("api_connect_src_blocked_or_risky")
    if existing_widget["relative_widget_script"]:
        risks.append("existing_relative_widget_script_cannot_infer_api_base_url")
    if duplicate_ids:
        risks.append("duplicate_html_ids")
    best_selector_duplicate_ids = candidates[0].get("selector_blocking_duplicate_ids") if candidates else {}
    best_selector_multiple_matches = candidates[0].get("selector_multiple_matches") if candidates else {}
    if best_selector_duplicate_ids:
        risks.append("ambiguous_recommended_selectors")
    if best_selector_multiple_matches and "ambiguous_recommended_selectors" not in risks:
        risks.append("ambiguous_recommended_selectors")
    if api_base_url_problem:
        risks.append("unsafe_api_base_url")
    if widget_src_problem:
        risks.append("unsafe_widget_src")
    if page_url_problem:
        risks.append("unsafe_page_url")
    data_auto_init_blocking_risks = sorted(risk for risk in risks if risk in DATA_AUTO_INIT_BLOCKING_RISKS)
    data_auto_init_review_risks = sorted(risk for risk in risks if risk not in DATA_AUTO_INIT_BLOCKING_RISKS)
    fallback_resolved_risks = (
        sorted(set(data_auto_init_blocking_risks) & FALLBACK_FLOATING_RESOLVABLE_RISKS)
        if allow_fallback_floating
        else []
    )
    fallback_blocking_risks = [
        risk for risk in data_auto_init_blocking_risks if risk not in FALLBACK_FLOATING_RESOLVABLE_RISKS
    ]
    fallback_review_risks = sorted(set(data_auto_init_review_risks + fallback_resolved_risks))
    url_validation = {
        "api_base_url": normalized_api_base_url,
        "api_base_url_error": api_base_url_problem,
        "widget_src": normalized_widget_src,
        "widget_src_error": widget_src_problem,
        "page_url": effective_page_url,
        "page_url_error": page_url_problem,
        "ok": not any([api_base_url_problem, widget_src_problem, page_url_problem]),
    }
    recommendation = None
    selector_recommendation = None
    selected_blocking_risks = data_auto_init_blocking_risks
    selected_review_risks = data_auto_init_review_risks
    data_auto_init_ready = bool(candidates) and not data_auto_init_blocking_risks
    if candidates:
        best = candidates[0]
        submit = best.get("submit") or {}
        selector_recommendation = {
            "mode": "data_auto_init",
            "ready": data_auto_init_ready,
            "blocking_risks": data_auto_init_blocking_risks,
            "review_risks": data_auto_init_review_risks,
            "inline_init_avoided": True,
            "url_validation_ok": url_validation["ok"],
            "attachToSearchInput": best["input"]["selector"],
            "attachAfterSelector": submit.get("selector", ""),
            "csp_widget_src_allowed": csp["widget_src_allowed"],
            "csp_api_connect_allowed": csp["api_connect_allowed"],
            "selectors_unique": best.get("selectors_unique") is True,
            "selector_match_counts": best.get("selector_match_counts") or {},
            "selector_multiple_matches": best.get("selector_multiple_matches") or {},
            "selector_duplicate_ids": best.get("selector_duplicate_ids") or {},
            "selector_blocking_duplicate_ids": best.get("selector_blocking_duplicate_ids") or {},
            "csp_allowlist_hint": (
                f"Allow {csp['widget_src_origin']} in "
                f"{(csp.get('widget_src_blocking_directives') or ['script-src'])[0]}"
                if csp["external_widget_src_risky"]
                else ""
            ),
            "csp_api_allowlist_hint": (
                f"Allow {csp['api_base_url_origin']} in "
                f"{(csp.get('api_connect_blocking_directives') or ['connect-src'])[0]}"
                if csp["api_connect_risky"]
                else ""
            ),
            "snippet": build_data_auto_init_snippet(
                widget_src=normalized_widget_src,
                mall_id=mall_id,
                api_key=api_key,
                attach_to_search_input=best["input"]["selector"],
                attach_after_selector=submit.get("selector", ""),
                trigger_title=trigger_title,
            ),
        }
        recommendation = selector_recommendation
    if allow_fallback_floating and (not candidates or fallback_resolved_risks):
        fallback_recommendation = build_fallback_floating_recommendation(
            widget_src=normalized_widget_src,
            mall_id=mall_id,
            api_key=api_key,
            trigger_title=trigger_title,
            blocking_risks=fallback_blocking_risks,
            review_risks=fallback_review_risks,
            url_validation_ok=url_validation["ok"],
            csp=csp,
        )
        if not candidates or fallback_recommendation["ready"]:
            recommendation = fallback_recommendation
            selected_blocking_risks = fallback_blocking_risks
            selected_review_risks = fallback_review_risks
            data_auto_init_ready = bool(fallback_recommendation["ready"])
    return {
        "name": name,
        "page_url": effective_page_url,
        "mall_id": str(mall_id or "").strip(),
        "ok": (
            bool(candidates)
            and url_validation["ok"]
            and not bool(best_selector_duplicate_ids)
            and not bool(best_selector_multiple_matches)
        )
        or bool(allow_fallback_floating and recommendation and recommendation.get("ready")),
        "candidate_count": len(candidates),
        "search_candidates": candidates[:5],
        "recommendation": recommendation,
        **({"selector_recommendation": selector_recommendation} if selector_recommendation else {}),
        "duplicate_html_ids": duplicate_ids,
        "csp": csp,
        "existing_widget": existing_widget,
        "url_validation": url_validation,
        "risks": risks,
        "blocking_risks": selected_blocking_risks,
        "review_risks": selected_review_risks,
        "data_auto_init_ready": data_auto_init_ready,
    }


def read_source(source: str, timeout: int) -> tuple[str, str, dict[str, Any]]:
    if re.match(r"^https?://", source, re.IGNORECASE):
        request = urllib.request.Request(
            source,
            headers={"User-Agent": "HaeorumAISearchWidgetIntegrationProbe/1.0"},
        )
        started = time.perf_counter()
        try:
            with open_public_http_request(request, timeout=timeout) as response:
                charset = response.headers.get_content_charset() or "utf-8"
                body = response.read().decode(charset, errors="replace")
                csp_headers = response.headers.get_all("Content-Security-Policy", []) or []
                return source, body, {
                    "source_type": "url",
                    "status": response.status,
                    "elapsed_ms": round((time.perf_counter() - started) * 1000, 1),
                    "content_security_policy": csp_headers,
                }
        except urllib.error.URLError as exc:
            return source, "", {"source_type": "url", "error": str(exc), "elapsed_ms": round((time.perf_counter() - started) * 1000, 1)}
    path = Path(source)
    raw = path.read_bytes()
    return (
        str(path),
        raw.decode("utf-8", errors="replace"),
        {
            "source_type": "file",
            "path": str(path),
            "source_fingerprint": {
                "algorithm": "sha256",
                "digest": hashlib.sha256(raw).hexdigest(),
                "size_bytes": len(raw),
            },
        },
    )


def analyze_source(
    source: str,
    args: argparse.Namespace,
    *,
    page_url: str = "",
    api_base_url: str = "",
    widget_src: str = "",
    mall_id: str = "",
    api_key: str = "",
    trigger_title: str = "",
    site: dict[str, Any] | None = None,
    source_index: int | None = None,
    source_variant: str = "",
    allow_fallback_floating: bool = False,
) -> dict[str, Any]:
    name, body, source_info = read_source(source, args.timeout)
    effective_mall_id = str(mall_id or args.mall_id or "").strip()
    effective_api_key = str(api_key or args.api_key or "").strip()
    effective_trigger_title = str(trigger_title or args.trigger_title or DEFAULT_TRIGGER_TITLE)
    effective_api_base_url = str(api_base_url or args.api_base_url or DEFAULT_API_BASE_URL).strip()
    effective_widget_src = str(widget_src or args.widget_src or "").strip()
    site_info = {
        "site_name": str((site or {}).get("name") or "").strip(),
        "mall_id": effective_mall_id,
        "origin": str((site or {}).get("origin") or "").strip(),
        "source": source,
        **({"source_index": source_index} if source_index is not None else {}),
        **({"source_variant": source_variant} if source_variant else {}),
    }
    if source_info.get("error"):
        return {
            "name": name,
            "ok": False,
            **site_info,
            **source_info,
            "risks": ["fetch_failed"],
        }
    return {
        **analyze_html_source(
            name,
            body,
            api_base_url=effective_api_base_url,
            widget_src=effective_widget_src,
            mall_id=effective_mall_id,
            api_key=effective_api_key,
            trigger_title=effective_trigger_title,
            response_csp_policies=source_info.get("content_security_policy") or [],
            page_url=page_url,
            allow_fallback_floating=allow_fallback_floating,
        ),
        **site_info,
        **source_info,
    }


def build_report_from_sites(args: argparse.Namespace, sites_path: str) -> dict[str, Any]:
    sites = load_probe_site_configs(Path(sites_path))
    base_dir = Path(sites_path).resolve().parent
    pages = []
    for site in sites:
        api_base_url = str(site.get("api_base_url") or args.api_base_url or DEFAULT_API_BASE_URL).rstrip("/")
        widget_src = site_widget_src(site, api_base_url, str(args.widget_src or ""))
        mall_id = str(site["mall_id"])
        api_key = str(site.get("api_key") or args.api_key or "").strip()
        trigger_title = str(site.get("trigger_title") or args.trigger_title or DEFAULT_TRIGGER_TITLE)
        page_url = str(site.get("url") or "").strip()
        allow_fallback_floating = bool(site.get("allow_fallback_floating") or getattr(args, "allow_fallback_floating", False))
        source_entries = probe_source_entries(site, base_dir=base_dir)
        for entry in source_entries:
            source = str(entry.get("source") or "")
            pages.append(
                analyze_source(
                    source,
                    args,
                    page_url=page_url,
                    api_base_url=api_base_url,
                    widget_src=widget_src,
                    mall_id=mall_id,
                    api_key=api_key,
                    trigger_title=trigger_title,
                    site=site,
                    source_index=int(entry.get("source_index") or len(pages) + 1),
                    source_variant=str(entry.get("variant") or ""),
                    allow_fallback_floating=allow_fallback_floating,
                )
            )
        if not source_entries:
            pages.append(
                {
                    "name": str(site.get("name") or mall_id),
                    "ok": False,
                    "site_name": str(site.get("name") or "").strip(),
                    "mall_id": mall_id,
                    "origin": str(site.get("origin") or "").strip(),
                    "page_url": page_url,
                    "source": "",
                    "risks": ["missing_probe_source"],
                }
            )
    return build_report_payload(pages, site_count=len(sites), site_config=sites_path)


def build_report_payload(pages: list[dict[str, Any]], *, site_count: int = 0, site_config: str = "") -> dict[str, Any]:
    ok = all(page.get("ok") for page in pages) if pages else False
    pages_with_candidates = sum(1 for page in pages if int(page.get("candidate_count") or 0) > 0)
    pages_ready = sum(1 for page in pages if page.get("data_auto_init_ready") is True)
    pages_with_blocking_risks = sum(1 for page in pages if page.get("blocking_risks"))
    manual_install_summary = build_manual_install_summary(pages)
    return {
        "ok": ok,
        "not_operational_readiness": True,
        **({"site_config": site_config, "site_count": site_count} if site_config else {}),
        "page_count": len(pages),
        "pages_with_candidates": pages_with_candidates,
        "pages_ready_for_data_auto_init": pages_ready,
        "pages_with_blocking_risks": pages_with_blocking_risks,
        "pages_with_external_widget_csp_risk": sum(
            1 for page in pages if "external_widget_src_blocked_or_risky" in (page.get("risks") or [])
        ),
        "pages_with_api_connect_csp_risk": sum(
            1 for page in pages if "api_connect_src_blocked_or_risky" in (page.get("risks") or [])
        ),
        "pages_with_unsafe_widget_url_risk": sum(
            1
            for page in pages
            if {"unsafe_api_base_url", "unsafe_widget_src", "unsafe_page_url"} & set(page.get("risks") or [])
        ),
        "manual_install_summary": manual_install_summary,
        "pages": pages,
    }


def slugify_filename(value: Any, fallback: str) -> str:
    text = str(value or "").strip().lower()
    slug = re.sub(r"[^a-z0-9._-]+", "-", text).strip("-._")
    slug = re.sub(r"-{2,}", "-", slug)
    return (slug or fallback)[:80]


def recommendation_selector_confidence(page: dict[str, Any], recommendation: dict[str, Any] | None) -> str:
    if not recommendation:
        return "none"
    mode = str(recommendation.get("mode") or "")
    if mode == "fallback_floating":
        return "fallback"
    if not recommendation.get("ready"):
        return "low"
    if recommendation.get("selectors_unique") is not True:
        return "low"
    counts = recommendation.get("selector_match_counts") or {}
    input_count = int(counts.get("input") or 0)
    submit_count = int(counts.get("submit") or 0)
    if input_count == 1 and submit_count == 1:
        return "high"
    if input_count == 1:
        return "medium"
    return "low"


def recommendation_selector_source(page: dict[str, Any], recommendation: dict[str, Any] | None) -> str:
    if not recommendation:
        return "none"
    if recommendation.get("mode") == "fallback_floating":
        return "fallback_floating"
    candidates = page.get("search_candidates") or []
    if candidates:
        best = candidates[0]
        score = best.get("score")
        selector = ((best.get("input") or {}).get("selector") or "").strip()
        return f"detected_search_input:score={score}:selector={selector}"
    return "detected_search_input"


def install_action_for(page: dict[str, Any], recommendation: dict[str, Any] | None) -> str:
    if not recommendation:
        return "capture_pc_mobile_html_or_fix_search_template_before_insert"
    if recommendation.get("blocking_risks"):
        return "fix_blocking_risks_before_insert"
    if recommendation.get("mode") == "fallback_floating":
        return "insert_fallback_floating_data_auto_init_script"
    if not recommendation.get("attachAfterSelector"):
        return "insert_data_auto_init_script_then_manually_verify_button_placement"
    return "insert_data_auto_init_script"


def build_manual_install_summary(pages: list[dict[str, Any]]) -> dict[str, Any]:
    plan_pages = [manual_install_plan_entry(index, page) for index, page in enumerate(pages, start=1)]
    return {
        "page_count": len(plan_pages),
        "ready_pages": sum(1 for page in plan_pages if page.get("ready") is True),
        "manual_review_pages": sum(1 for page in plan_pages if page.get("manual_review_required") is True),
        "fallback_floating_pages": sum(1 for page in plan_pages if page.get("install_mode") == "fallback_floating"),
        "selector_high_confidence_pages": sum(1 for page in plan_pages if page.get("selector_confidence") == "high"),
        "csp_change_pages": sum(1 for page in plan_pages if page.get("csp_change_required") is True),
    }


def manual_install_plan_entry(
    index: int,
    page: dict[str, Any],
    snippet_file: str = "",
    preview_file: str = "",
) -> dict[str, Any]:
    recommendation = page.get("recommendation") if isinstance(page.get("recommendation"), dict) else None
    blocking_risks = list(page.get("blocking_risks") or [])
    review_risks = list(page.get("review_risks") or [])
    selector_confidence = recommendation_selector_confidence(page, recommendation)
    selector_source = recommendation_selector_source(page, recommendation)
    manual_review_required = (
        not bool((recommendation or {}).get("ready"))
        or bool(blocking_risks)
        or bool(review_risks)
        or selector_confidence in {"low", "fallback", "none"}
    )
    csp = page.get("csp") or {}
    return {
        "page_index": index,
        "name": page.get("name"),
        "site_name": page.get("site_name") or "",
        "mall_id": page.get("mall_id") or "",
        "page_url": page.get("page_url") or "",
        "source": page.get("source") or page.get("path") or page.get("name") or "",
        "source_type": page.get("source_type") or "",
        "source_variant": page.get("source_variant") or "",
        "ready": bool((recommendation or {}).get("ready")),
        "install_mode": str((recommendation or {}).get("mode") or "manual_review"),
        "suggested_action": install_action_for(page, recommendation),
        "manual_review_required": manual_review_required,
        "selector_confidence": selector_confidence,
        "selector_source": selector_source,
        "selectors": {
            "attach_to_search_input": str((recommendation or {}).get("attachToSearchInput") or ""),
            "attach_after_selector": str((recommendation or {}).get("attachAfterSelector") or ""),
            "match_counts": (recommendation or {}).get("selector_match_counts") or {},
            "multiple_matches": (recommendation or {}).get("selector_multiple_matches") or {},
            "duplicate_ids": (recommendation or {}).get("selector_duplicate_ids") or {},
            "blocking_duplicate_ids": (recommendation or {}).get("selector_blocking_duplicate_ids") or {},
            "unique": bool((recommendation or {}).get("selectors_unique")),
        },
        "fallback_floating": bool((recommendation or {}).get("fallbackFloating")),
        "blocking_risks": blocking_risks,
        "review_risks": review_risks,
        "csp_change_required": bool(
            (recommendation or {}).get("csp_allowlist_hint") or (recommendation or {}).get("csp_api_allowlist_hint")
        ),
        "csp_allowlist": {
            "script_src_origin": csp.get("widget_src_origin") or "",
            "connect_src_origin": csp.get("api_base_url_origin") or "",
            "script_src_hint": str((recommendation or {}).get("csp_allowlist_hint") or ""),
            "connect_src_hint": str((recommendation or {}).get("csp_api_allowlist_hint") or ""),
            "script_src_allowed": bool((recommendation or {}).get("csp_widget_src_allowed")),
            "connect_src_allowed": bool((recommendation or {}).get("csp_api_connect_allowed")),
        },
        "url_validation": page.get("url_validation") or {},
        "snippet_file": snippet_file,
        "preview_file": preview_file,
    }


def build_manual_install_plan(
    report: dict[str, Any],
    *,
    snippet_outputs: list[dict[str, Any]] | None = None,
) -> dict[str, Any]:
    snippet_by_index = {
        int(output.get("page_index") or 0): str(output.get("snippet_file") or "")
        for output in (snippet_outputs or [])
    }
    preview_by_index = {
        int(output.get("page_index") or 0): str(output.get("preview_file") or "")
        for output in (snippet_outputs or [])
    }
    pages = [
        manual_install_plan_entry(
            index,
            page,
            snippet_file=snippet_by_index.get(index, ""),
            preview_file=preview_by_index.get(index, ""),
        )
        for index, page in enumerate(report.get("pages") or [], start=1)
    ]
    return {
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "source": "widget_integration_probe",
        "review_required": True,
        "not_operational_readiness": True,
        "operator_context": "developer_unavailable_saved_html_install_plan",
        **build_manual_install_summary(report.get("pages") or []),
        "pages": pages,
    }


def manual_install_plan_markdown(plan: dict[str, Any]) -> str:
    lines = [
        "# Widget Manual Install Plan",
        "",
        f"- Review required: `{plan.get('review_required')}`",
        f"- Not operational readiness evidence: `{plan.get('not_operational_readiness')}`",
        f"- Operator context: `{plan.get('operator_context')}`",
        f"- Ready pages: `{plan.get('ready_pages')}`",
        f"- Manual review pages: `{plan.get('manual_review_pages')}`",
        f"- Fallback floating pages: `{plan.get('fallback_floating_pages')}`",
        f"- CSP change pages: `{plan.get('csp_change_pages')}`",
        "",
        "| Page | Mall | Mode | Confidence | Action | Manual review | Snippet | Preview |",
        "| --- | --- | --- | --- | --- | --- | --- | --- |",
    ]
    for page in plan.get("pages") or []:
        lines.append(
            "| {page} | `{mall}` | `{mode}` | `{confidence}` | `{action}` | `{review}` | `{snippet}` | `{preview}` |".format(
                page=str(page.get("site_name") or page.get("name") or page.get("page_index") or ""),
                mall=str(page.get("mall_id") or ""),
                mode=str(page.get("install_mode") or ""),
                confidence=str(page.get("selector_confidence") or ""),
                action=str(page.get("suggested_action") or ""),
                review=page.get("manual_review_required"),
                snippet=str(page.get("snippet_file") or "not generated"),
                preview=str(page.get("preview_file") or "not generated"),
            )
        )
    for page in plan.get("pages") or []:
        lines.extend(
            [
                "",
                f"## {page.get('site_name') or page.get('name') or page.get('page_index')}",
                "",
                f"- Source: `{page.get('source') or 'n/a'}`",
                f"- Page URL: `{page.get('page_url') or 'n/a'}`",
                f"- Selector source: `{page.get('selector_source')}`",
                f"- Input selector: `{(page.get('selectors') or {}).get('attach_to_search_input') or ''}`",
                f"- Anchor selector: `{(page.get('selectors') or {}).get('attach_after_selector') or ''}`",
                f"- Blocking risks: `{', '.join(page.get('blocking_risks') or []) or 'none'}`",
                f"- Review risks: `{', '.join(page.get('review_risks') or []) or 'none'}`",
                f"- CSP script hint: `{(page.get('csp_allowlist') or {}).get('script_src_hint') or 'none'}`",
                f"- CSP connect hint: `{(page.get('csp_allowlist') or {}).get('connect_src_hint') or 'none'}`",
                f"- Preview file: `{page.get('preview_file') or 'not generated'}`",
            ]
        )
    return "\n".join(lines)


def inject_snippet_preview_html(body: str, snippet: str) -> str:
    marker = f"\n<!-- {PREVIEW_INSERTION_MARKER} -->\n"
    insertion = marker + snippet.strip() + "\n"
    text = str(body or "")
    lower = text.lower()
    for closing_tag in ("</body>", "</html>"):
        index = lower.rfind(closing_tag)
        if index >= 0:
            return text[:index] + insertion + text[index:]
    return text.rstrip() + insertion


def write_preview_file(
    *,
    target: Path,
    index: int,
    base: str,
    page: dict[str, Any],
    snippet: str,
) -> str:
    source = str(page.get("source") or page.get("path") or "").strip()
    if not snippet or not source or re.match(r"^https?://", source, re.IGNORECASE):
        return ""
    source_path = Path(source)
    if not source_path.exists() or not source_path.is_file():
        return ""
    try:
        body = source_path.read_text(encoding="utf-8", errors="replace")
    except OSError:
        return ""
    preview_dir = target / "previews"
    preview_dir.mkdir(parents=True, exist_ok=True)
    preview_path = preview_dir / f"{index:03d}-{base}.preview.html"
    preview_path.write_text(inject_snippet_preview_html(body, snippet) + "\n", encoding="utf-8")
    return str(preview_path)


def file_sha256(path: Path) -> dict[str, Any]:
    raw = path.read_bytes()
    return {"algorithm": "sha256", "digest": hashlib.sha256(raw).hexdigest(), "size_bytes": len(raw)}


def validate_preview_html_body(
    body: str,
    snippet: str,
    *,
    page_index: Any = None,
    name: Any = None,
    mall_id: str = "",
    preview_file: str = "",
    snippet_file: str = "",
    source_file: str = "",
    attach_to_search_input: str = "",
    attach_after_selector: str = "",
    fallback_floating: bool = False,
    preview_fingerprint: Mapping[str, Any] | None = None,
) -> dict[str, Any]:
    problems = []
    expected_selectors = {
        "attach_to_search_input": str(attach_to_search_input or "").strip(),
        "attach_after_selector": str(attach_after_selector or "").strip(),
    }
    details: dict[str, Any] = {
        "page_index": page_index,
        "name": name,
        "mall_id": mall_id or "",
        "preview_file": preview_file,
        "snippet_file": snippet_file,
        "source_file": source_file,
        "exists": True,
        "marker_count": 0,
        "data_auto_init_script_count": 0,
        "snippet_embedded": False,
        "inserted_before_body_close": False,
        "fallback_floating": bool(fallback_floating),
        "expected_selectors": expected_selectors,
        "selector_match_counts": {},
        "selectors_ok": True,
        "preview_fingerprint": dict(preview_fingerprint or {}),
        "problems": problems,
    }
    marker_count = str(body or "").count(PREVIEW_INSERTION_MARKER)
    details["marker_count"] = marker_count
    if marker_count != 1:
        problems.append(f"preview_marker_count:{marker_count}")
    elements = parse_html(body)
    data_auto_init_count = sum(
        1
        for element in elements
        if element.get("tag") == "script" and html_truthy_attr((element.get("attrs") or {}).get("data-hai-auto-init"))
    )
    details["data_auto_init_script_count"] = data_auto_init_count
    if data_auto_init_count < 1:
        problems.append("data_auto_init_script_missing")
    if data_auto_init_count > 1:
        problems.append(f"data_auto_init_script_multiple:{data_auto_init_count}")
    selector_match_counts: dict[str, int] = {}
    if not fallback_floating:
        for key, selector in expected_selectors.items():
            if not selector:
                continue
            match_count = selector_match_count(elements, selector)
            selector_match_counts[key] = match_count
            if match_count == 0:
                problems.append(f"{key}_selector_missing")
            elif match_count > 1:
                problems.append(f"{key}_selector_multiple:{match_count}")
    details["selector_match_counts"] = selector_match_counts
    details["selectors_ok"] = not any(
        problem.endswith("_selector_missing") or "_selector_multiple:" in problem for problem in problems
    )
    snippet_text = str(snippet or "").strip()
    details["snippet_embedded"] = bool(snippet_text and snippet_text in str(body or ""))
    if not details["snippet_embedded"]:
        problems.append("snippet_not_embedded")
    lower = str(body or "").lower()
    marker_index = str(body or "").find(PREVIEW_INSERTION_MARKER)
    body_close_index = lower.rfind("</body>")
    details["inserted_before_body_close"] = bool(marker_index >= 0 and (body_close_index < 0 or marker_index < body_close_index))
    if not details["inserted_before_body_close"]:
        problems.append("preview_marker_not_before_body_close")
    return {**details, "ok": not problems}


def preview_validation_entry(output: dict[str, Any]) -> dict[str, Any]:
    preview_file = str(output.get("preview_file") or "")
    snippet_file = str(output.get("snippet_file") or "")
    source_file = str(output.get("source_file") or "")
    problems = []
    details: dict[str, Any] = {
        "page_index": output.get("page_index"),
        "name": output.get("name"),
        "mall_id": output.get("mall_id") or "",
        "preview_file": preview_file,
        "snippet_file": snippet_file,
        "source_file": source_file,
        "exists": False,
        "marker_count": 0,
        "data_auto_init_script_count": 0,
        "snippet_embedded": False,
        "inserted_before_body_close": False,
        "fallback_floating": bool(output.get("fallback_floating")),
        "expected_selectors": {
            "attach_to_search_input": str(output.get("attach_to_search_input") or ""),
            "attach_after_selector": str(output.get("attach_after_selector") or ""),
        },
        "selector_match_counts": {},
        "selectors_ok": False,
        "preview_fingerprint": {},
        "problems": problems,
    }
    if not preview_file:
        problems.append("preview_file_not_generated")
        return {**details, "ok": False}
    preview_path = Path(preview_file)
    if not preview_path.exists() or not preview_path.is_file():
        problems.append("preview_file_missing")
        return {**details, "ok": False}
    try:
        body = preview_path.read_text(encoding="utf-8", errors="replace")
        preview_fingerprint = file_sha256(preview_path)
    except OSError as exc:
        problems.append(f"preview_file_unreadable:{type(exc).__name__}")
        return {**details, "ok": False}
    snippet = ""
    snippet_problem = ""
    if snippet_file and Path(snippet_file).exists():
        try:
            snippet = Path(snippet_file).read_text(encoding="utf-8").strip()
        except OSError as exc:
            snippet_problem = f"snippet_file_unreadable:{type(exc).__name__}"
    else:
        snippet_problem = "snippet_file_missing"
    validation = validate_preview_html_body(
        body,
        snippet,
        page_index=output.get("page_index"),
        name=output.get("name"),
        mall_id=output.get("mall_id") or "",
        preview_file=preview_file,
        snippet_file=snippet_file,
        source_file=source_file,
        attach_to_search_input=str(output.get("attach_to_search_input") or ""),
        attach_after_selector=str(output.get("attach_after_selector") or ""),
        fallback_floating=bool(output.get("fallback_floating")),
        preview_fingerprint=preview_fingerprint,
    )
    if snippet_problem:
        validation["problems"] = [
            problem for problem in validation.get("problems", []) if problem != "snippet_not_embedded"
        ] + [snippet_problem]
        validation["snippet_embedded"] = False
        validation["ok"] = False
    return validation


def build_preview_validation(
    outputs: list[dict[str, Any]],
    *,
    manifest_extra: dict[str, Any] | None = None,
) -> dict[str, Any]:
    validations = [preview_validation_entry(output) for output in outputs if not output.get("skipped")]
    report = {
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "source": "widget_integration_probe",
        "review_required": True,
        "not_operational_readiness": True,
        "page_count": len(outputs),
        "validated_preview_count": len(validations),
        "ok_preview_count": sum(1 for item in validations if item.get("ok")),
        "failed_preview_count": sum(1 for item in validations if not item.get("ok")),
        "ok": bool(validations) and all(item.get("ok") for item in validations),
        "previews": validations,
    }
    if manifest_extra:
        for key in ("simulation_marker", "simulation_only", "simulation_note"):
            if key in manifest_extra:
                report[key] = manifest_extra[key]
        report["not_operational_readiness"] = True
    return report


def preview_validation_markdown(report: dict[str, Any]) -> str:
    lines = [
        "# Widget Preview Validation",
        "",
        f"- OK: `{report.get('ok')}`",
        f"- Review required: `{report.get('review_required')}`",
        f"- Not operational readiness evidence: `{report.get('not_operational_readiness')}`",
        f"- Validated previews: `{report.get('validated_preview_count')}`",
        f"- Failed previews: `{report.get('failed_preview_count')}`",
        "",
        "| Page | Mall | OK | Selectors OK | Selector matches | Marker count | Auto init scripts | Problems | Preview |",
        "| --- | --- | --- | --- | --- | --- | --- | --- |",
    ]
    for item in report.get("previews") or []:
        lines.append(
            "| {page} | `{mall}` | `{ok}` | `{selectors_ok}` | `{selector_matches}` | `{marker}` | `{auto}` | {problems} | `{preview}` |".format(
                page=str(item.get("name") or item.get("page_index") or ""),
                mall=str(item.get("mall_id") or ""),
                ok=item.get("ok"),
                selectors_ok=item.get("selectors_ok"),
                selector_matches=item.get("selector_match_counts") or {},
                marker=item.get("marker_count"),
                auto=item.get("data_auto_init_script_count"),
                problems=", ".join(item.get("problems") or []) or "none",
                preview=str(item.get("preview_file") or ""),
            )
        )
    return "\n".join(lines)


def write_snippet_bundle(
    report: dict[str, Any],
    output_dir: str | Path,
    manifest_extra: dict[str, Any] | None = None,
) -> dict[str, Any]:
    target = Path(output_dir)
    target.mkdir(parents=True, exist_ok=True)
    clear_previous_snippet_bundle(target)
    outputs = []
    snippet_count = 0
    preview_count = 0
    for index, page in enumerate(report.get("pages") or [], start=1):
        recommendation = page.get("recommendation") if isinstance(page, dict) else None
        snippet = str((recommendation or {}).get("snippet") or "")
        label = page.get("site_name") or page.get("mall_id") or page.get("name") or f"page-{index}"
        base = slugify_filename(f"{page.get('mall_id') or ''}-{label}", f"page-{index}")
        entry = {
            "page_index": index,
            "name": page.get("name"),
            "site_name": page.get("site_name") or "",
            "mall_id": page.get("mall_id") or "",
            "page_url": page.get("page_url") or "",
            "ready": bool((recommendation or {}).get("ready")),
            "blocking_risks": page.get("blocking_risks") or [],
            "review_risks": page.get("review_risks") or [],
            "skipped": not bool(snippet),
            "snippet_file": "",
            "preview_file": "",
            "preview_skipped": True,
            "source_file": page.get("source") or page.get("path") or "",
            "attach_to_search_input": str((recommendation or {}).get("attachToSearchInput") or ""),
            "attach_after_selector": str((recommendation or {}).get("attachAfterSelector") or ""),
            "fallback_floating": bool((recommendation or {}).get("fallbackFloating")),
        }
        if snippet:
            snippet_count += 1
            snippet_path = target / f"{index:03d}-{base}.html"
            snippet_path.write_text(snippet + "\n", encoding="utf-8")
            entry["snippet_file"] = str(snippet_path)
            preview_file = write_preview_file(
                target=target,
                index=index,
                base=base,
                page=page,
                snippet=snippet,
            )
            if preview_file:
                preview_count += 1
                entry["preview_file"] = preview_file
                entry["preview_skipped"] = False
        outputs.append(entry)
    manifest = {
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "source": "widget_integration_probe",
        "review_required": True,
        "not_operational_readiness": True,
        "contains_public_api_keys": True,
        "page_count": len(report.get("pages") or []),
        "snippet_count": snippet_count,
        "preview_count": preview_count,
        "outputs": outputs,
    }
    if manifest_extra:
        manifest.update(manifest_extra)
        manifest["source"] = "widget_integration_probe"
        manifest["review_required"] = True
        manifest["not_operational_readiness"] = True
        manifest["contains_public_api_keys"] = True
    manual_plan = build_manual_install_plan(report, snippet_outputs=outputs)
    if manifest_extra:
        for key in ("simulation_marker", "simulation_only", "simulation_note"):
            if key in manifest_extra:
                manual_plan[key] = manifest_extra[key]
        manual_plan["not_operational_readiness"] = True
    preview_validation = build_preview_validation(outputs, manifest_extra=manifest_extra)
    manual_plan_json = target / "manual-install-plan.json"
    manual_plan_markdown = target / "manual-install-plan.md"
    preview_validation_json = target / "preview-validation.json"
    preview_validation_markdown_path = target / "preview-validation.md"
    manifest["manual_install_plan_json"] = str(manual_plan_json)
    manifest["manual_install_plan_markdown"] = str(manual_plan_markdown)
    manifest["preview_validation_json"] = str(preview_validation_json)
    manifest["preview_validation_markdown"] = str(preview_validation_markdown_path)
    manifest["preview_validation_ok"] = preview_validation.get("ok")
    manifest["preview_validation_failed_count"] = preview_validation.get("failed_preview_count")
    manifest["manual_install_ready_pages"] = manual_plan.get("ready_pages")
    manifest["manual_install_review_pages"] = manual_plan.get("manual_review_pages")
    manifest["manual_install_csp_change_pages"] = manual_plan.get("csp_change_pages")
    manifest["preview_count"] = preview_count
    (target / "manifest.json").write_text(json.dumps(manifest, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    manual_plan_json.write_text(json.dumps(manual_plan, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    manual_plan_markdown.write_text(manual_install_plan_markdown(manual_plan) + "\n", encoding="utf-8")
    preview_validation_json.write_text(json.dumps(preview_validation, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    preview_validation_markdown_path.write_text(preview_validation_markdown(preview_validation) + "\n", encoding="utf-8")
    (target / "README.md").write_text(snippet_bundle_markdown(manifest) + "\n", encoding="utf-8")
    return manifest


def clear_previous_snippet_bundle(target: Path) -> None:
    manifest_path = target / "manifest.json"
    if not manifest_path.exists():
        return
    try:
        manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return
    if not isinstance(manifest, dict) or manifest.get("source") != "widget_integration_probe":
        return
    for snippet_path in target.glob("[0-9][0-9][0-9]-*.html"):
        try:
            snippet_path.unlink()
        except OSError:
            pass
    preview_dir = target / "previews"
    if preview_dir.exists():
        for preview_path in preview_dir.glob("[0-9][0-9][0-9]-*.preview.html"):
            try:
                preview_path.unlink()
            except OSError:
                pass


def snippet_bundle_markdown(manifest: dict[str, Any]) -> str:
    lines = [
        "# Widget Snippet Bundle",
        "",
        f"- Review required: `{manifest.get('review_required')}`",
        f"- Not operational readiness evidence: `{manifest.get('not_operational_readiness')}`",
        f"- Contains public API keys for page insertion: `{manifest.get('contains_public_api_keys')}`",
        f"- Snippet count: `{manifest.get('snippet_count')}`",
        f"- Preview count: `{manifest.get('preview_count')}`",
        f"- Preview validation OK: `{manifest.get('preview_validation_ok')}`",
        f"- Preview validation: `{manifest.get('preview_validation_json')}`",
        f"- Manual install plan: `{manifest.get('manual_install_plan_json')}`",
        f"- Manual review pages: `{manifest.get('manual_install_review_pages')}`",
        f"- CSP change pages: `{manifest.get('manual_install_csp_change_pages')}`",
        "",
        "| Page | Mall | Ready | Blocking risks | Snippet | Preview |",
        "| --- | --- | --- | --- | --- | --- |",
    ]
    for item in manifest.get("outputs") or []:
        lines.append(
            "| {page} | `{mall}` | `{ready}` | {risks} | `{snippet}` | `{preview}` |".format(
                page=str(item.get("site_name") or item.get("name") or item.get("page_index") or ""),
                mall=str(item.get("mall_id") or ""),
                ready=item.get("ready"),
                risks=", ".join(item.get("blocking_risks") or []) or "none",
                snippet=str(item.get("snippet_file") or "not generated"),
                preview=str(item.get("preview_file") or "not generated"),
            )
        )
    return "\n".join(lines)


def build_report(args: argparse.Namespace) -> dict[str, Any]:
    sites_path = str(getattr(args, "sites", "") or "").strip()
    if sites_path:
        return build_report_from_sites(args, sites_path)

    pages = []
    for source in getattr(args, "input", []) or []:
        pages.append(analyze_source(source, args, allow_fallback_floating=bool(getattr(args, "allow_fallback_floating", False))))
    return build_report_payload(pages)


def to_markdown(report: dict[str, Any]) -> str:
    lines = [
        "# Widget Integration Probe",
        "",
        f"- OK: `{report.get('ok')}`",
        f"- Pages: `{report.get('page_count')}`",
        f"- Pages with candidates: `{report.get('pages_with_candidates')}`",
        f"- Pages ready for data auto init: `{report.get('pages_ready_for_data_auto_init')}`",
        f"- Pages with blocking risks: `{report.get('pages_with_blocking_risks')}`",
        "",
    ]
    for page in report.get("pages", []):
        lines.extend(
            [
                f"## {page.get('name')}",
                "",
                f"- OK: `{page.get('ok')}`",
                f"- Site: `{page.get('site_name') or 'n/a'}`",
                f"- Mall: `{page.get('mall_id') or 'n/a'}`",
                f"- Page URL: `{page.get('page_url') or 'n/a'}`",
                f"- Data auto init ready: `{page.get('data_auto_init_ready')}`",
                f"- Blocking risks: `{', '.join(page.get('blocking_risks') or []) or 'none'}`",
                f"- Review risks: `{', '.join(page.get('review_risks') or []) or 'none'}`",
                f"- Risks: `{', '.join(page.get('risks') or []) or 'none'}`",
                f"- Candidate count: `{page.get('candidate_count', 0)}`",
            ]
        )
        url_validation = page.get("url_validation") or {}
        if url_validation:
            url_errors = [
                error
                for error in (
                    url_validation.get("api_base_url_error"),
                    url_validation.get("widget_src_error"),
                    url_validation.get("page_url_error"),
                )
                if error
            ]
            lines.extend(
                [
                    f"- URL validation OK: `{url_validation.get('ok')}`",
                    f"- URL validation errors: `{'; '.join(url_errors) or 'none'}`",
                ]
            )
        recommendation = page.get("recommendation")
        if recommendation:
            lines.extend(
                [
                    f"- Recommended input selector: `{recommendation.get('attachToSearchInput')}`",
                    f"- Recommended anchor selector: `{recommendation.get('attachAfterSelector')}`",
                    f"- Recommended data auto init ready: `{recommendation.get('ready')}`",
                    f"- Recommended selectors unique: `{recommendation.get('selectors_unique')}`",
                    f"- Recommended selector match counts: `{recommendation.get('selector_match_counts') or {}}`",
                    f"- URL validation OK: `{recommendation.get('url_validation_ok')}`",
                    f"- CSP external widget allowed: `{recommendation.get('csp_widget_src_allowed')}`",
                    f"- CSP allowlist hint: `{recommendation.get('csp_allowlist_hint') or 'none'}`",
                    f"- CSP API connect allowed: `{recommendation.get('csp_api_connect_allowed')}`",
                    f"- CSP API connect allowlist hint: `{recommendation.get('csp_api_allowlist_hint') or 'none'}`",
                    "",
                    "```html",
                    recommendation.get("snippet", ""),
                    "```",
                    "",
                ]
            )
        else:
            lines.append("")
    return "\n".join(lines)


def parse_args(argv: list[str]) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Probe saved mall HTML or URLs and generate a data-hai-auto-init widget snippet.")
    parser.add_argument("--input", action="append", default=[], help="HTML file path or HTTP(S) URL. Repeat for PC/mobile pages.")
    parser.add_argument("--sites", default="", help="Representative site config JSON. Uses each site's url or widget_probe_source(s).")
    parser.add_argument("--api-base-url", default=DEFAULT_API_BASE_URL)
    parser.add_argument("--widget-src", default="", help="Explicit widget.js URL. Defaults to <api-base-url>/widget.js.")
    parser.add_argument("--mall-id", default="replace-with-mall-id")
    parser.add_argument("--api-key", default="replace-with-public-api-key")
    parser.add_argument("--trigger-title", default=DEFAULT_TRIGGER_TITLE)
    parser.add_argument(
        "--allow-fallback-floating",
        action="store_true",
        help="Generate an opt-in floating widget snippet when no usable search input selector is found.",
    )
    parser.add_argument("--timeout", type=int, default=10)
    parser.add_argument("--output", default="")
    parser.add_argument("--markdown-output", default="")
    parser.add_argument("--snippets-output-dir", default="", help="Write per-page data-hai-auto-init snippets and a manifest.")
    args = parser.parse_args(argv)
    if not args.input and not args.sites:
        parser.error("one of --input or --sites is required")
    return args


def main(argv: list[str] | None = None) -> int:
    args = parse_args(argv or sys.argv[1:])
    report = build_report(args)
    if args.snippets_output_dir:
        manifest = write_snippet_bundle(report, args.snippets_output_dir)
        report["snippet_bundle"] = {
            "output_dir": str(Path(args.snippets_output_dir)),
            "manifest": str(Path(args.snippets_output_dir) / "manifest.json"),
            "manual_install_plan": str(Path(args.snippets_output_dir) / "manual-install-plan.json"),
            "manual_install_plan_markdown": str(Path(args.snippets_output_dir) / "manual-install-plan.md"),
            "preview_validation": str(Path(args.snippets_output_dir) / "preview-validation.json"),
            "preview_validation_markdown": str(Path(args.snippets_output_dir) / "preview-validation.md"),
            "snippet_count": manifest.get("snippet_count"),
            "preview_count": manifest.get("preview_count"),
            "preview_validation_ok": manifest.get("preview_validation_ok"),
            "review_required": manifest.get("review_required"),
            "not_operational_readiness": manifest.get("not_operational_readiness"),
            "manual_install_ready_pages": manifest.get("manual_install_ready_pages"),
            "manual_install_review_pages": manifest.get("manual_install_review_pages"),
            "manual_install_csp_change_pages": manifest.get("manual_install_csp_change_pages"),
        }
    text = json.dumps(report, ensure_ascii=False, indent=2)
    print(text)
    if args.output:
        Path(args.output).parent.mkdir(parents=True, exist_ok=True)
        Path(args.output).write_text(text + "\n", encoding="utf-8")
    if args.markdown_output:
        Path(args.markdown_output).parent.mkdir(parents=True, exist_ok=True)
        Path(args.markdown_output).write_text(to_markdown(report) + "\n", encoding="utf-8")
    return 0 if report["ok"] else 1


if __name__ == "__main__":
    raise SystemExit(main())
